### ISSUE TITLE
SyntaxError: Unexpected token (

### ISSUE THREAD

**Issue by manelcomiche** [SimonLeclere/discord-hangman#2] opened 2021-02-19 22:02 UTC
I found a error:  #gatherPlayersFromMessage(channel) {
SyntaxError: Unexpected token (

> /rbd/pnpm-volume/fcc59e12-4c16-4b25-9ba5-0f6a674bf7b5/node_modules/.registry.npmjs.org/discord-hangman/1.0.3/node_modules/discord-hangman/index.js:38

**Comment by SimonLeclere** [comment] 2021-02-19 22:45
Hello,
this is really weird because on line 38 of the index.js file, there are no parenthesis.
In what context do you encounter this error?
Can you send the complete error?

Simon.

**Comment by manelcomiche** [comment] 2021-02-20 09:24
I have this error when i'm using the `hangman.creator`, the error is only this...

**Comment by SimonLeclere** [comment] 2021-02-20 09:35
Can you show me your code?
Which node version do you use?

**Comment by manelcomiche** [comment] 2021-02-20 09:50
This is my code
```js
const hangman = require('discord-hangman');

module.exports.run = async (client, message, args, perm) => {
    if(perm) return message.channel.send(perm);

await hangman.create(message.channel, 'random')
}
```

I'm using node 12.x

**Comment by SimonLeclere** [comment] 2021-02-20 10:21
Okay thanks for these informations, I will do some tests on my side and try to reproduce your error.

**Comment by SimonLeclere** [comment] 2021-02-20 10:48
I solved the error!
It seems that it comes from the use of private fields in the HangmanManager class (in the module).
Updating Node should fix the problem.
If you really want to keep your version of Node.JS, you can simply remove all the `#` from the `node_modules\discord-hangman\index.js` file.

If this solution has solved your problem, feel free to close the issue :)

**Comment by SimonLeclere** [comment] 2021-02-23 13:20
closed for inactivity 😴

**Closed as completed by SimonLeclere** 2021-02-23 13:20 UTC
